export const SET_DEVICE_INFORMATION_ON_RESIZE =
  "SET_DEVICE_INFORMATION_ON_RESIZE";

export const SUBMIT_LOGIN_LOADING = "SUBMIT_LOGIN_LOADING";
export const SUBMIT_LOGIN_SUCCESS = "SUBMIT_LOGIN_SUCCESS";
export const SUBMIT_LOGIN_FAILURE = "SUBMIT_LOGIN_FAILURE";
export const RESET_LOGIN_SUCCESS = "RESET_LOGIN_SUCCESS";

export const GET_RECRUTIER_JOBS_LOADING = "GET_RECRUTIER_JOBS_LOADING";
export const GET_RECRUTIER_JOBS_SUCCESS = "GET_RECRUTIER_JOBS_SUCCESS";
export const GET_RECRUTIER_JOBS_FAILURE = "GET_RECRUTIER_JOBS_FAILURE";

export const POST_NEW_JOB_LOADING = "POST_NEW_JOB_LOADING";
export const POST_NEW_JOB_SUCCESS = "POST_NEW_JOB_SUCCESS";
export const POST_NEW_JOB_FAILURE = "POST_NEW_JOB_FAILURE";

export const GET_JOB_CANDIDATES_LOADING = "GET_JOB_CANDIDATES_LOADING";
export const GET_JOB_CANDIDATES_SUCCESS = "GET_JOB_CANDIDATES_SUCCESS";
export const GET_JOB_CANDIDATES_FAILURE = "GET_JOB_CANDIDATES_FAILURE";
